'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SIFAC.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32px_Crystal_Clear_action_reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32px_Crystal_Clear_action_reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _32px_Crystal_Clear_mimetype_source_moc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_32px_Crystal_Clear_mimetype_source_moc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Default() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Default", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _Stop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_Stop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Anular() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Anular", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Aprobar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Aprobar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Autorizar_Pedido() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Autorizar_Pedido", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BackgroundImage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BackgroundImage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property balanza() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("balanza", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Bonificaciones() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bonificaciones", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Boxes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Boxes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Buscar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Buscar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Cancel16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cancel16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CargosDependecias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CargosDependecias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carpeta() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carpeta", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Carpeta1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Carpeta1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Catalogos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Catalogos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Catalogos2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Catalogos2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CatalogoValor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CatalogoValor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CerrarSesion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CerrarSesion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Consultar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Consultar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Empleados() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Empleados", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fondo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fondo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Forward() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Forward", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guardar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guardar16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardar16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Guardar32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Guardar32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icon6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniciarSesion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniciarSesion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property IniciarSesion1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("IniciarSesion1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaST__Cobalt__Find() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Find", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaST__Cobalt__Fonts_Folders() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Fonts_Folders", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaST__Cobalt__Internet_File() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Internet_File", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaST__Cobalt__Library_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Library_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LaST__Cobalt__Users_Folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LaST__Cobalt__Users_Folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El registro se ha actualizado satisfactoriamente..
        '''</summary>
        Friend ReadOnly Property MsgActualizado() As String
            Get
                Return ResourceManager.GetString("MsgActualizado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El registro se ha guardado satisfactoriamente..
        '''</summary>
        Friend ReadOnly Property MsgAgregado() As String
            Get
                Return ResourceManager.GetString("MsgAgregado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen datos para generar esta búsqueda..
        '''</summary>
        Friend ReadOnly Property MsgBusqueda() As String
            Get
                Return ResourceManager.GetString("MsgBusqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Está seguro de eliminar el registro seleccionado?..
        '''</summary>
        Friend ReadOnly Property MsgConfirmarEliminar() As String
            Get
                Return ResourceManager.GetString("MsgConfirmarEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Desea salir sin guardar los cambios?..
        '''</summary>
        Friend ReadOnly Property MsgConfirmarGuardar() As String
            Get
                Return ResourceManager.GetString("MsgConfirmarGuardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to El registro se ha eliminado satisfactoriamente..
        '''</summary>
        Friend ReadOnly Property MsgEliminado() As String
            Get
                Return ResourceManager.GetString("MsgEliminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No es posible cambiar el código de repuesto cargado desde la base de datos..
        '''</summary>
        Friend ReadOnly Property MsgNoPuedeCambiarCodigo() As String
            Get
                Return ResourceManager.GetString("MsgNoPuedeCambiarCodigo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Campo Obligatorio.
        '''</summary>
        Friend ReadOnly Property MsgObligatorio() As String
            Get
                Return ResourceManager.GetString("MsgObligatorio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No existen datos para generar el reporte..
        '''</summary>
        Friend ReadOnly Property MsgReporte() As String
            Get
                Return ResourceManager.GetString("MsgReporte", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to La operación solicitada no puede ser efectuada. El registro está siendo usado por otro usuario.
        '''</summary>
        Friend ReadOnly Property MsgReservado() As String
            Get
                Return ResourceManager.GetString("MsgReservado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ¿Desea salir SIN GUARDAR los cambios realizados?.
        '''</summary>
        Friend ReadOnly Property MsgSalirSinGuardar() As String
            Get
                Return ResourceManager.GetString("MsgSalirSinGuardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NuevoRegProducto() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NuevoRegProducto", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Office2003Olive() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Office2003Olive", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property opts_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("opts_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property paste_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("paste_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pedidos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pedidos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prefs_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prefs_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Procesar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Procesar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Productos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Productos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ProveedorEstilo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ProveedorEstilo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Prueba() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Prueba", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Reporte_de_Facturas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reporte_de_Facturas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Rol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Rol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Run() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Run", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Salir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Salir2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Salir2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Secuencias() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Secuencias", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Seguridad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Seguridad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Sello() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sello", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UbicacionesGeograficas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UbicacionesGeograficas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UbicacionGeograf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UbicacionGeograf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UbicacionGeografica() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UbicacionGeografica", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property updated24x24() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updated24x24", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property User2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("User2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Usuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Usuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Xy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Xy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zonas() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zonas", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Zonas1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Zonas1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
